// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DatabaseFrist.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFrist.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<SP_GetCustomerOrderHistoryResult>> SP_GetCustomerOrderHistoryAsync(string customerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetDataByDateResult>> SP_GetDataByDateAsync(DateOnly? begin, DateOnly? end, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateProductPricesResult>> SP_UpdateProductPricesAsync(int? categoryID, double? percentage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
