// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFrist.Context;
using DatabaseFrist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFrist.Context.Configurations
{
    public partial class DisplayProductsAbovePriceConfiguration : IEntityTypeConfiguration<DisplayProductsAbovePrice>
    {
        public void Configure(EntityTypeBuilder<DisplayProductsAbovePrice> entity)
        {
            entity.ToView("DisplayProductsAbovePrices");

            entity.Property(e => e.ProductID).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DisplayProductsAbovePrice> entity);
    }
}
