// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFrist.Context;
using DatabaseFrist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFrist.Context.Configurations
{
    public partial class LateShippedOrderConfiguration : IEntityTypeConfiguration<LateShippedOrder>
    {
        public void Configure(EntityTypeBuilder<LateShippedOrder> entity)
        {
            entity.ToView("LateShippedOrders");

            entity.Property(e => e.CustomerID).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LateShippedOrder> entity);
    }
}
