// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseFrist.Models;

[Keyless]
[Table("PriceUpdateLog")]
public partial class PriceUpdateLog
{
    public int ProductID { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? OldPrice { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? NewPrice { get; set; }

    public DateOnly? UpdateDate { get; set; }
}